# Generated by Django 4.1.7 on 2023-03-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('styling', models.CharField(max_length=250)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='posts.post')),
            ],
        ),
    ]
